/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edums.GUI;

import edums.DB;
import edums.Class;
import edums.Student;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Diogo
 */
public class EditClassFrame extends javax.swing.JFrame {    
    DB tempDB = new DB("teste.bin");
    edums.School s = new edums.School("School");    
    private static Class c1;
    private List<Student> students;
    
    public EditClassFrame(Class c1) {
        
        this.c1 = c1;
        students = new ArrayList<>();
        initComponents();
        //s = tempDB.importData();
        
        this.EDIT_DenomTEXT.setText(c1.getUnitDenomination());
        this.EDIT_TypeSELECT.setSelectedItem(c1.getTypeClass());
        this.EDIT_cUnitSELECT.setSelectedItem(c1.getCurricularUnit());
        this.EDIT_classesPWeek_SPINNER.setValue(c1.getClassesPerWeek());
        this.EDIT_hoursPClass_SPINNER.setValue(c1.getHoursPerClass());
        
        for (int i = 0; i < c1.getNumStudents(); i++) {
            students.add(c1.getStudent(i));
        }
        
        DenomLabel.setVisible(false);
        pstudentsList.setVisible(false);
        addToClass_BUTTON.setVisible(false);
        
        updateMembersList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner2 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanelCLASS = new javax.swing.JPanel();
        addClassTEXT = new javax.swing.JLabel();
        EDIT_DenomTEXT = new javax.swing.JTextField();
        EditClassButton = new javax.swing.JButton();
        CancelButton_CLASS = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        EDIT_TypeSELECT = new javax.swing.JComboBox<>();
        EDIT_cUnitSELECT = new javax.swing.JComboBox<>();
        EDIT_classesPWeek_SPINNER = new javax.swing.JSpinner();
        EDIT_hoursPClass_SPINNER = new javax.swing.JSpinner();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        DenomLabel = new javax.swing.JLabel();
        totalMembers_LABEL = new javax.swing.JLabel();
        addToClass_BUTTON = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pstudentsList = new javax.swing.JList<>();
        removeMemberButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        membersList = new javax.swing.JList<>();
        addMemberButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 600));

        addClassTEXT.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addClassTEXT.setText("Edit Class");

        EDIT_DenomTEXT.setText("Denom");

        EditClassButton.setText("Edit Class");
        EditClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditClassButtonActionPerformed(evt);
            }
        });

        CancelButton_CLASS.setText("Cancel");
        CancelButton_CLASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton_CLASSActionPerformed(evt);
            }
        });

        EDIT_TypeSELECT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T", "TP", "P" }));
        EDIT_TypeSELECT.setToolTipText("");

        EDIT_cUnitSELECT.setModel(new DefaultComboBoxModel(s.getcUnits().toArray()));

        EDIT_classesPWeek_SPINNER.setModel(new javax.swing.SpinnerNumberModel(0, 0, 6, 1));
        EDIT_classesPWeek_SPINNER.setToolTipText("");

        EDIT_hoursPClass_SPINNER.setModel(new javax.swing.SpinnerNumberModel(0, 0, 6, 1));
        EDIT_hoursPClass_SPINNER.setToolTipText("");

        label1.setName(""); // NOI18N
        label1.setText("Hours/Class:");

        label2.setName(""); // NOI18N
        label2.setText("Classes/Week:");

        DenomLabel.setText("jLabel1");

        String total = "(TOTAL: " + membersList.getModel().getSize() + ")";
        totalMembers_LABEL.setText(total);

        addToClass_BUTTON.setText("Add To Class");
        addToClass_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToClass_BUTTONActionPerformed(evt);
            }
        });

        pstudentsList.setModel(new DefaultListModel());
        pstudentsList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pstudentsListaddMemberButtonActionPerformed(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(pstudentsList);

        removeMemberButton.setText("Remove Member");
        removeMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMemberButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(membersList);

        addMemberButton.setText("Add Member");
        addMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberButtonActionPerformed1(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("MEMBERS");

        javax.swing.GroupLayout jPanelCLASSLayout = new javax.swing.GroupLayout(jPanelCLASS);
        jPanelCLASS.setLayout(jPanelCLASSLayout);
        jPanelCLASSLayout.setHorizontalGroup(
            jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCLASSLayout.createSequentialGroup()
                .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCLASSLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addClassTEXT)
                            .addGroup(jPanelCLASSLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EDIT_cUnitSELECT, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelCLASSLayout.createSequentialGroup()
                                        .addComponent(EDIT_DenomTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(EDIT_TypeSELECT, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DenomLabel))
                                .addGap(23, 23, 23)
                                .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EDIT_hoursPClass_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EDIT_classesPWeek_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCLASSLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanelCLASSLayout.createSequentialGroup()
                                .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanelCLASSLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(totalMembers_LABEL))
                                        .addGroup(jPanelCLASSLayout.createSequentialGroup()
                                            .addComponent(removeMemberButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(addMemberButton))
                                        .addComponent(jScrollPane1)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCLASSLayout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(addToClass_BUTTON)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelCLASSLayout.createSequentialGroup()
                                .addComponent(CancelButton_CLASS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditClassButton)))))
                .addContainerGap())
        );
        jPanelCLASSLayout.setVerticalGroup(
            jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCLASSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addClassTEXT)
                .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCLASSLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDIT_TypeSELECT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDIT_DenomTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDIT_hoursPClass_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(DenomLabel))
                    .addGroup(jPanelCLASSLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCLASSLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDIT_cUnitSELECT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDIT_classesPWeek_SPINNER, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CancelButton_CLASS)
                            .addComponent(EditClassButton)))
                    .addGroup(jPanelCLASSLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalMembers_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCLASSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeMemberButton)
                    .addComponent(addMemberButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addToClass_BUTTON)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCLASS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCLASS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButton_CLASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton_CLASSActionPerformed
        Frame fr[] = EditClassFrame.getFrames();
        for (Frame f : fr) {
            if(f instanceof EditClassFrame)
            f.dispose();
        }
    }//GEN-LAST:event_CancelButton_CLASSActionPerformed

    private void EditClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditClassButtonActionPerformed
        boolean isValid = true;
        DenomLabel.setVisible(false);
        
        if(EDIT_DenomTEXT.getText().isEmpty()){
            DenomLabel.setText("* Denomination field required!");
            DenomLabel.setVisible(true);
            isValid = false;
        }
        System.out.println(""+EDIT_classesPWeek_SPINNER.equals(0)); //Tenho que ir buscar o model para obter o valor
        
        if(isValid){
            EduMSFrame temp = null;
            Frame fr[] = EditClassFrame.getFrames();
            DB tempDB = new DB("teste.bin");
            for (Frame f : fr) {
                if(f instanceof EduMSFrame){
                    temp = (EduMSFrame) f;
                    temp.getSchool().removeClass(c1);
                    c1.setUnitDenomination(EDIT_DenomTEXT.getText());
                    c1.setTypeClass(EDIT_TypeSELECT.getSelectedItem().toString());
                    c1.setCurricularUnit(EDIT_cUnitSELECT.getSelectedItem().toString());
                    c1.setHoursPerClass((int)EDIT_hoursPClass_SPINNER.getValue());
                    c1.setClassesPerWeek((int)EDIT_classesPWeek_SPINNER.getValue());

                    
                    temp.getSchool().addClass(c1);
                    tempDB.exportData(temp.getSchool());
                }
             }
            temp.updateList();
            for (Frame f : fr) {
                if(f instanceof EditClassFrame)
                f.dispose();
            }
        }
    }//GEN-LAST:event_EditClassButtonActionPerformed
    private void updateMembersList(){
        edums.DB db1 = new edums.DB("teste.bin");
        s = db1.importData();
        Student.setIdTotal(s.getStudents().size());
        
        DefaultListModel StudentsListModel = (DefaultListModel) pstudentsList.getModel();
        StudentsListModel.removeAllElements();
        
        for(int i = 0; i < s.getStudents().size();i++){
            StudentsListModel.addElement(s.getStudents().get(i).getName());
        }
        for (int i = 0; i < students.size(); i++) {
            StudentsListModel.removeElement(students.get(i).getName());
        }
        membersList.setModel(new DefaultListModel());
        DefaultListModel membersListModel = (DefaultListModel) membersList.getModel();
        membersListModel.removeAllElements();

        for(int i = 0; i < students.size();i++){
          membersListModel.addElement(students.get(i).getName());
        }
    }
    
    private void addMemberButtonActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberButtonActionPerformed1

        updateMembersList();

        pstudentsList.setVisible(true);
        addToClass_BUTTON.setVisible(true);
    }//GEN-LAST:event_addMemberButtonActionPerformed1

    private void pstudentsListaddMemberButtonActionPerformed(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pstudentsListaddMemberButtonActionPerformed

    }//GEN-LAST:event_pstudentsListaddMemberButtonActionPerformed

    private void addToClass_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToClass_BUTTONActionPerformed
        /*edums.DB db1 = new edums.DB("teste.bin");
        s = db1.importData();

        String student2Add = pstudentsList.getSelectedValue().toString();
        for(int i = 0; i < s.getStudents().size(); i++){
            if(s.getStudents().get(i).getName() ==  student2Add){
                students.add(s.getStudents().get(i));
            }
        }

        updateMembersList();*/
        for(int i = 0; i < s.getStudents().size(); i++){
            if(s.getStudents().get(i).getName().equals(pstudentsList.getSelectedValue())){
                c1.associateStudent(s.getStudents().get(i));
                students.add(s.getStudents().get(i));
            }
        }
        updateMembersList();
    }//GEN-LAST:event_addToClass_BUTTONActionPerformed

    private void removeMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMemberButtonActionPerformed
        for(int i = 0; i < students.size(); i++){
            if(students.get(i).getName().equals(membersList.getSelectedValue())){
                c1.desassociateStudent(students.get(i));
                students.remove(students.get(i));
            }
        }
        updateMembersList();
    }//GEN-LAST:event_removeMemberButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditClassFrame ed = new EditClassFrame(c1);
                ed.EDIT_DenomTEXT.setText(c1.getUnitDenomination());
                ed.EDIT_TypeSELECT.setSelectedItem(c1.getTypeClass());
                ed.EDIT_cUnitSELECT.setSelectedItem(c1.getCurricularUnit());
                ed.EDIT_classesPWeek_SPINNER.setValue(c1.getClassesPerWeek());
                ed.EDIT_hoursPClass_SPINNER.setValue(c1.getHoursPerClass());
                ed.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton_CLASS;
    private javax.swing.JLabel DenomLabel;
    private javax.swing.JTextField EDIT_DenomTEXT;
    private javax.swing.JComboBox<String> EDIT_TypeSELECT;
    private javax.swing.JComboBox<String> EDIT_cUnitSELECT;
    private javax.swing.JSpinner EDIT_classesPWeek_SPINNER;
    private javax.swing.JSpinner EDIT_hoursPClass_SPINNER;
    private javax.swing.JButton EditClassButton;
    private javax.swing.JLabel addClassTEXT;
    private javax.swing.JButton addMemberButton;
    private javax.swing.JButton addToClass_BUTTON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelCLASS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JList<String> membersList;
    private javax.swing.JList<String> pstudentsList;
    private javax.swing.JButton removeMemberButton;
    private javax.swing.JLabel totalMembers_LABEL;
    // End of variables declaration//GEN-END:variables
}
